name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6

    - name: Install dependencies
      run: pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     # 테스트 스크립트 실행
    #     python test.py

    - name: Deploy to AWS
      run: |
        # AWS CLI를 이용한 로그인
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1

        # AWS에 배포 스크립트 실행
        # 예: Elastic Beanstalk, EC2, S3 등
